/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5f5e5f",
        "on-error": "#ffffff",
        "secondary-container": "#645efb",
        "surface-bright": "#f9f9fb",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "surface-container": "#eeeef0",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fffbff",
        "on-tertiary-container": "#868380",
        "primary-fixed": "#e5e2e3",
        "inverse-surface": "#2f3132",
        "on-tertiary-fixed-variant": "#484644",
        "secondary-fixed-dim": "#c3c0ff",
        "surface-variant": "#e2e2e4",
        "surface": "#f9f9fb",
        "tertiary-fixed-dim": "#cac6c2",
        "error": "#ba1a1a",
        "on-primary-container": "#858384",
        "on-primary-fixed": "#1c1b1c",
        "inverse-on-surface": "#f0f0f2",
        "on-tertiary-fixed": "#1d1b19",
        "on-primary-fixed-variant": "#474647",
        "on-background": "#1a1c1d",
        "secondary": "#4b41e1",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e4",
        "outline-variant": "#c7c6ca",
        "primary": "#000000",
        "surface-dim": "#d9dadc",
        "primary-container": "#1c1b1c",
        "surface-container-low": "#f3f3f5",
        "on-secondary-fixed-variant": "#3323cc",
        "inverse-primary": "#c8c6c7",
        "on-surface": "#1a1c1d",
        "surface-container-high": "#e8e8ea",
        "tertiary-fixed": "#e6e2de",
        "on-primary": "#ffffff",
        "background": "#f9f9fb",
        "secondary-fixed": "#e2dfff",
        "outline": "#77777b",
        "tertiary-container": "#1d1b19",
        "on-surface-variant": "#46464a",
        "primary-fixed-dim": "#c8c6c7",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0f0069"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "12px",
        "stack-sm": "8px",
        "stack-lg": "24px",
        "container-margin": "24px",
        "panel-padding": "16px",
        "unit": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "-apple-system", "sans-serif"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "display-sm": ["Inter"],
        "body-sm": ["Inter"],
        "metadata-lg": ["Inter"],
        "mono-label": ["Space Mono", "monospace"],
        "metadata-sm": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "headline-md": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "display-sm": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "metadata-lg": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "mono-label": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "metadata-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-sm": ["16px", { "lineHeight": "22px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
